// Geographical and delivery configuration extracted from the legacy JS
// NOTE: This is a direct data module (no React/DOM code).

export type TarifsLivraison = Record<string, { domicile: number; stopDesk: number }>
export type CommunesParWilaya = Record<number, string[]>
export type BureauNoest = { code: string; nom: string }

// Optional display names for wilayas (Arabic). Keys are wilaya IDs as numbers.
export const wilayaNames: Record<number, string> = {
  1: "أدرار",
  2: "الشلف",
  3: "الأغواط",
  4: "أم البواقي",
  5: "باتنة",
  6: "بجاية",
  7: "بسكرة",
  8: "بشار",
  9: "البليدة",
  10: "البويرة",
  11: "تمنراست",
  12: "تبسة",
  13: "تلمسان",
  14: "تيارت",
  15: "تيزي وزو",
  16: "الجزائر",
  17: "الجلفة",
  18: "جيجل",
  19: "سطيف",
  20: "سعيدة",
  21: "سكيكدة",
  22: "سيدي بلعباس",
  23: "عنابة",
  24: "قالمة",
  25: "قسنطينة",
  26: "المدية",
  27: "مستغانم",
  28: "المسيلة",
  29: "معسكر",
  30: "ورقلة",
  31: "وهران",
  32: "البيض",
  33: "إليزي",
  34: "برج بوعريريج",
  35: "بومرداس",
  36: "الطارف",
  37: "تندوف",
  38: "تيسمسيلت",
  39: "الوادي",
  40: "خنشلة",
  41: "سوق أهراس",
  42: "تيبازة",
  43: "ميلة",
  44: "عين الدفلى",
  45: "النعامة",
  46: "عين تموشنت",
  47: "غرداية",
  48: "غليزان",
  49: "تيميمون",
  51: "أولاد جلال",
  52: "بني عباس",
  53: "عين صالح",
  55: "تقرت",
  57: "المغير",
  58: "المنيعة",
}

// Tarifs de livraison par wilaya (domicile / stopDesk)
export const tarifsLivraison: TarifsLivraison = {
  "16": { domicile: 500, stopDesk: 250 },
  "35": { domicile: 500, stopDesk: 300 },
  "9": { domicile: 550, stopDesk: 250 },
  "42": { domicile: 550, stopDesk: 250 },
  "15": { domicile: 600, stopDesk: 300 },
  "10": { domicile: 650, stopDesk: 300 },
  "26": { domicile: 650, stopDesk: 250 },
  "2": { domicile: 700, stopDesk: 350 },
  "6": { domicile: 700, stopDesk: 350 },
  "14": { domicile: 700, stopDesk: 350 },
  "19": { domicile: 700, stopDesk: 350 },
  "25": { domicile: 700, stopDesk: 350 },
  "31": { domicile: 700, stopDesk: 350 },
  "4": { domicile: 750, stopDesk: 350 },
  "5": { domicile: 750, stopDesk: 350 },
  "13": { domicile: 750, stopDesk: 350 },
  "18": { domicile: 750, stopDesk: 350 },
  "21": { domicile: 750, stopDesk: 350 },
  "22": { domicile: 750, stopDesk: 350 },
  "23": { domicile: 750, stopDesk: 350 },
  "27": { domicile: 750, stopDesk: 350 },
  "28": { domicile: 750, stopDesk: 350 },
  "29": { domicile: 750, stopDesk: 350 },
  "34": { domicile: 750, stopDesk: 350 },
  "38": { domicile: 750, stopDesk: 350 },
  "41": { domicile: 750, stopDesk: 350 },
  "43": { domicile: 750, stopDesk: 350 },
  "44": { domicile: 750, stopDesk: 350 },
  "46": { domicile: 750, stopDesk: 350 },
  "48": { domicile: 750, stopDesk: 350 },
  "12": { domicile: 800, stopDesk: 350 },
  "20": { domicile: 800, stopDesk: 350 },
  "24": { domicile: 800, stopDesk: 350 },
  "36": { domicile: 800, stopDesk: 350 },
  "40": { domicile: 800, stopDesk: 350 },
  "7": { domicile: 900, stopDesk: 350 },
  "51": { domicile: 900, stopDesk: 350 },
  "3": { domicile: 1000, stopDesk: 500 },
  "17": { domicile: 1000, stopDesk: 500 },
  "30": { domicile: 1000, stopDesk: 500 },
  "39": { domicile: 1000, stopDesk: 500 },
  "47": { domicile: 1000, stopDesk: 500 },
  "55": { domicile: 1000, stopDesk: 500 },
  "57": { domicile: 1000, stopDesk: 500 },
  "58": { domicile: 1000, stopDesk: 500 },
  "8": { domicile: 1100, stopDesk: 600 },
  "32": { domicile: 1100, stopDesk: 600 },
  "45": { domicile: 1100, stopDesk: 600 },
  "52": { domicile: 1100, stopDesk: 600 },
  "1": { domicile: 1400, stopDesk: 700 },
  "37": { domicile: 1400, stopDesk: 600 },
  "49": { domicile: 1400, stopDesk: 700 },
  "11": { domicile: 1850, stopDesk: 1000 },
  "53": { domicile: 1850, stopDesk: 1000 },
  "33": { domicile: 2000, stopDesk: 1000 },
}

// Communes par wilaya (copied from the provided JS).
// NOTE: Only a subset was pasted in your snippet; this can be extended further if needed.
export const communesParWilaya: CommunesParWilaya = {
  1: [
    "Adrar",
    "Akabli",
    "Aoulef",
    "Bouda",
    "Fenoughil",
    "Inozghmir",
    "O Ahmed Timmi",
    "Reggane",
    "Sali",
    "Sbaa",
    "Tamest",
    "Tamentit",
    "Timiaouine",
    "Timokten",
    "Tsabit",
    "Zaouiet Kounta",
  ],
  2: [
    "Ain Merane",
    "Bénairia",
    "Beni Haoua",
    "Beni Rached",
    "Boukadir",
    "Bouzghaia",
    "Chettia",
    "Chlef",
    "Dahra",
    "El Karimia",
    "El Marsa",
    "Harchoun",
    "Labiod Medjadja",
    "Oued Fodda",
    "Oued Sly",
    "Oum Drou",
    "Ouled Abbes",
    "Ouled Ben Abdelkader",
    "Ouled Fares",
    "Sidi Abderrahmane",
    "Sidi Akacha",
    "Sendjas",
    "Sobha",
    "Tadjna",
    "Talassa",
    "Taougrite",
    "Ténès",
    "Zeboudja",
  ],
  3: [
    "Aflou",
    "Ain Mahdi",
    "Ain Sidi Ali",
    "Beidha",
    "Bennacer Ben Chohra",
    "Brida",
    "El Assafia",
    "El Ghicha",
    "El Houaita",
    "Gueltat Sidi Saad",
    "Hadj Mechri",
    "Hassi Delaa",
    "Hassi R Mel",
    "Kheneg",
    "Ksar El Hirane",
    "Laghouat",
    "Oued Morra",
    "Sebgag",
    "Sidi Bouzid",
    "Sidi Makhlouf",
    "Tadjemout",
    "Tadjrouna",
    "Taouiala",
  ],
  4: [
    "Ain Babouche",
    "Ain Beida",
    "Ain Diss",
    "Ain Fakroun",
    "Ain Kercha",
    "Ain Zitoun",
    "Behir Chergui",
    "Berriche",
    "Bir Chouhada",
    "Dhala",
    "El Amiria",
    "El Belala",
    "El Fedjoudj Boughrar",
    "El Harmilia",
    "Fkirina",
    "Hanchir Toumghani",
    "Ksar Sbahi",
    "Meskiana",
    "Oued Nini",
    "Oum El Bouaghi",
    "Ouled Gacem",
    "Ouled Hamla",
    "Sigus",
    "Souk Naamane",
    "Zorg",
  ],
  5: [
    "Aïn Djasser",
    "Aïn Touta",
    "Aïn Yagout",
    "Arris",
    "Barika",
    "Batna",
    "Ben Foudhala El Hakania",
    "Bitam",
    "Boumia",
    "Boulhilat",
    "Boumagueur",
    "Bouzina",
    "Chemora",
    "Chir",
    "Djezzar",
    "Djerma",
    "El Hassi",
    "El Medher",
    "Fesdis",
    "Foum Toub",
    "Ghassira",
    "Gosbat",
    "Guigba",
    "Hidoussa",
    "Ichmoul",
    "Inoughissen",
    "Kimmel",
    "Ksar Bellezma",
    "Larbaa",
    "Lazrou",
    "Lemsane",
    "Maafa",
    "Menaa",
    "Merouana",
    "Ngaous",
    "Oued Chaaba",
    "Oued El Ma",
    "Oued Taga",
    "Ouled Ammar",
    "Ouled Aouf",
    "Ouled Fadel",
    "Ouled Sellam",
    "Ouled Si Slimane",
    "Ouyoun El Assafir",
    "Rahbat",
    "Ras El Aioun",
    "Seggana",
    "Sefiane",
    "Seriana",
    "Talkhamt",
    "Taxlent",
    "Tazoult",
    "Teniet El Abed",
    "Tigherghar",
    "Tighanimine",
    "Tilatou",
    "Timgad",
    "Tkout",
    "Zanat El Beida",
  ],
  6: [
    "Adekar",
    "Akbou",
    "Akfadou",
    "Ait Rizine",
    "Ait Smail",
    "Amalou",
    "Amizour",
    "Aokas",
    "Barbacha",
    "Béjaïa",
    "Beni Ksila",
    "Beni Maouch",
    "Boudjellil",
    "Boukhelifa",
    "Chellata",
    "Chemini",
    "Darguina",
    "El Kseur",
    "Ighram",
    "ifelain Ilmathen",
    "Kherrata",
    "Leflaye",
    "Melbou",
    "Mcisna",
    "Oued Ghir",
    "Ouzallaguen",
    "Seddouk",
    "Semaoun",
    "Sidi Aich",
    "Sidi Ayad",
    "Souk El Thenine",
    "Souk Oufella",
    "Taourirt Ighil",
    "Taskriout",
    "Tala Hamza",
    "Tazmalt",
    "Tibane",
    "Tichi",
    "Tifra",
    "Timzrit",
    "Tinabdher",
    "Tizi Nberber",
    "Toudja",
  ],
  7: [
    "Biskra",
    "Branis",
    "Chetma",
    "Djemorah",
    "El Ghrous",
    "El Hadjab",
    "El Kantara",
    "El Outaya",
    "Foughala",
    "Lichana",
    "Lioua",
    "Mchouneche",
    "Mekhadma",
    "Mlili",
    "Oumache",
    "Ourlal",
    "Sidi Okba",
    "Tolga",
    "Zeribet El Oued",
  ],
  8: [
    "Bechar",
    "Beni Ounif",
    "Boukais",
    "Erg Ferradj",
    "Kenadsa",
    "Lahmar",
    "Mechraa Houari B",
    "Meridja",
    "Mougheul",
    "Taghit",
  ],
  9: [
    "Ain Romana",
    "Beni Mered",
    "Beni Tamou",
    "Benkhelil",
    "Blida",
    "Bouarfa",
    "Boufarik",
    "Bouinan",
    "Bougara",
    "Chebli",
    "Cheffa",
    "Chrea",
    "Djebabra",
    "El Affroun",
    "Guerouaou",
    "Hammam Melouane",
    "Larbaa",
    "Meftah",
    "Mouzaia",
    "Oued El Alleug",
    "Oued Djer",
    "Ouled Selama",
    "Ouled Yaich",
    "Souhane",
    "Soumaa",
  ],
  10: [
    "Aghbalou",
    "Ahl El Ksar",
    "Ain Bessam",
    "Ain El Hadjar",
    "Ain El Turk",
    "Ain Laloui",
    "Ait Laaziz",
    "Aomar",
    "Ath Mansour",
    "Bechloul",
    "Bir Ghbalou",
    "Bordj Okhriss",
    "Bouira",
    "Bouderbala",
    "Boukram",
    "Chorfa",
    "Dechmia",
    "Dirah",
    "Djebahia",
    "El Adjiba",
    "El Asnam",
    "El Hachimia",
    "El Hakimia",
    "El Mokrani",
    "Guerrouma",
    "Haizer",
    "Hadjera Zerga",
    "Hanif",
    "Kadiria",
    "Lakhdaria",
    "Maala",
    "Maamora",
    "M'Chedallah",
    "Mezdour",
    "Oued El Berdi",
    "Ouled Rached",
    "Raouraoua",
    "Ridane",
    "Saharidj",
    "Sour El Ghozlane",
    "Souk El Khemis",
    "Taghzout",
    "Taguedit",
    "Zbarbar",
  ],
  11: ["Tamanghasset"],
  12: [
    "Aïn Zerga",
    "Bekkaria",
    "Bir Dheheb",
    "Bir El Ater",
    "Bir Mokadem",
    "Boukhadra",
    "Boulhaf Dyr",
    "Cheria",
    "El Aouinet",
    "El Kouif",
    "El Ma El Biodh",
    "El Mezeraa",
    "El Meridj",
    "El Ogla",
    "El Ogla",
    "Guorriguer",
    "Hammamet",
    "Lahouidjbet",
    "Morsott",
    "Ouenza",
    "Oum Ali",
    "Safsaf El Ouesra",
    "Stah Guentis",
    "Tébessa",
    "Thlidjene",
  ],
  13: [
    "Aïn Fetah",
    "Aïn Ghoraba",
    "Aïn Kebira",
    "Aïn Nehala",
    "Aïn Tallout",
    "Aïn Youcef",
    "Amieur",
    "Azails",
    "Bab El Assa",
    "Beni Bahdel",
    "Beni Boussaid",
    "Beni Mester",
    "Beni Ouarsous",
    "Beni Semiel",
    "Beni Snous",
    "Bouhlou",
    "Chetouane",
    "Djebala",
    "El Aricha",
    "El Bouihi",
    "El Fehoul",
    "El Gor",
    "Fellaoucene",
    "Ghazaouet",
    "Hammam Boughrara",
    "Hennaya",
    "Honaine",
    "Maghnia",
    "Mansourah",
    "Marsa Ben Mhidi",
    "Msirda Fouaga",
    "Nedroma",
    "Ouled Mimoun",
    "Ouled Riyah",
    "Remchi",
    "Sabra",
    "Sebaa Chioukh",
    "Sebdou",
    "Sidi Abdelli",
    "Sidi Djillali",
    "Sidi Medjahed",
    "Souahlia",
    "Souani",
    "Souk El Khemis",
    "Souk Thlata",
    "Terny Beni Hediel",
    "Tianet",
    "Tlemcen",
    "Zenata",
  ],
  14: [
    "Ain Bouchekif",
    "Ain Deheb",
    "Ain El Hadid",
    "Ain Kermes",
    "Bougara",
    "Chehaima",
    "Dahmouni",
    "Djillali Ben Amar",
    "Faidja",
    "Frenda",
    "Guertoufa",
    "Hamadia",
    "Ksar Chellala",
    "Madna",
    "Mahdia",
    "Mechraa Safa",
    "Medrissa",
    "Medroussa",
    "Meghila",
    "Mellakou",
    "Nadorah",
    "Naima",
    "Oued Lilli",
    "Rahouia",
    "Rechaiga",
    "Sebaine",
    "Sebt",
    "Serghine",
    "Sidi Abdelghani",
    "Sidi Abderrahmane",
    "Sidi Ali Mellal",
    "Sidi Bakhti",
    "Sidi Hosni",
    "Sougueur",
    "Tagdemt",
    "Takhemaret",
    "Tiaret",
    "Tidda",
    "Tousnina",
    "Zmalet El Emir Aek",
  ],
  15: [
    "Tizi Ouzou",
    "Ain El Hammam",
    "Akbil",
    "Freha",
    "Souamaa",
    "Mechtras",
    "Irdjen",
    "Timizart",
    "Makouda",
    "Draa El Mizan",
    "Tizi Ghenif",
    "Bounouh",
    "Ait Chaffaa",
    "Frikat",
    "Beni Aissi",
    "Iferhounene",
    "Azazga",
    "Yakouren",
    "Larba Nait Irathen",
    "Tizi Rached",
    "Zekri",
    "Ouaguenoun",
    "Ain Zaouia",
    "Ait Yahia",
    "Ait Mahmoud",
    "Maatkas",
    "Ait Boumehdi",
    "Abi Youcef",
    "Beni Douala",
    "Illilten",
    "Bouzeguen",
    "Ait Aggouacha",
    "Ouadhia",
    "Azeffoun",
    "Tigzirt",
    "Ait Aissa Mimoun",
    "Boghni",
    "Ifigha",
    "Ait Oumalou",
    "Tirmitine",
    "Akerrou",
    "Yatafen",
    "Draa Ben Khedda",
    "Ouacif",
    "Idjeur",
    "Mekla",
    "Tizi Nthleta",
    "Aghribs",
    "Iflissen",
    "Boudjima",
    "Aït Yahia Moussa",
    "Souk El Thenine",
    "Aït Khelil",
    "Sidi Naamane",
    "Iboudraren",
    "Mizrana",
    "Tadmait",
    "Ait Bouadou",
    "Assi Youcef",
  ],
  16: [
    "Alger Centre",
    "Ain Benian",
    "Ain Taya",
    "Baba Hassen",
    "Bab Azzouar",
    "Bab El Oued",
    "Bachedjerah",
    "Baraki",
    "Ben Aknoun",
    "Beni Messous",
    "Bir Mourad Rais",
    "Birkhadem",
    "Birtouta",
    "Bologhine Ibn Ziri",
    "Bordj El Bahri",
    "Bordj El Kiffan",
    "Bouzareah",
    "Bourouba",
    "Casbah",
    "Cheraga",
    "Dar El Beïda",
    "Dely Ibrahim",
    "Douera",
    "Draria",
    "El Achour",
    "El Biar",
    "El Harrach",
    "El Madania",
    "El Magharia",
    "El Mouradia",
    "Hammamet",
    "Hussein Dey",
    "Hydra",
    "Khraicia",
    "Kouba",
    "Les Eucalyptus",
    "Mohammadia",
    "Marsa",
    "Oued Koriche",
    "Oued Smar",
    "Ouled Chebel",
    "Ouled Fayet",
    "Rahmania",
    "Rais Hamidou",
    "Reghaia",
    "Rouiba",
    "Saoula",
    "Sidi Moussa",
    "Sidi Mhamed",
    "Souidania",
    "Staoueli",
    "Zeralda",
  ],
  17: [
    "Ain Chouhada",
    "Ain El Ibel",
    "Ain Fekka",
    "Ain Oussera",
    "Benhar",
    "Beni Yagoub",
    "Birine",
    "Bouira Lahdeb",
    "Charef",
    "Dar Chioukh",
    "Deldoul",
    "Djelfa",
    "Douis",
    "El Guedid",
    "El Idrissia",
    "Feidh El Botma",
    "Guernini",
    "Had Sahary",
    "Hassi Bahbah",
    "Hassi El Euch",
    "Hassi Fedoul",
    "Messaad",
    "Mliliha",
    "Moudjebara",
    "Sed Rahal",
    "Selmana",
    "Sidi Baizid",
    "Sidi Ladjel",
    "Tadmit",
    "Zaccar",
  ],
  18: [
    "Chekfa",
    "Djemaa Beni Habibi",
    "El Ancer",
    "El Aouana",
    "El Kennar Nouchfi",
    "El Milia",
    "Emir Abdelkader",
    "Jijel",
    "Kaous",
    "Settara",
    "Sidi Abdelaziz",
    "Sidi Maarouf",
    "Taher",
    "Texena",
  ],
  19: [
    "Ain Abessa",
    "Ain Azal",
    "Ain El Kebira",
    "Ain Lahdjar",
    "Ain Legraj",
    "Aïn Oulmane",
    "Ain Roua",
    "Ain Sebt",
    "Ait Tizi",
    "Amoucha",
    "Babor",
    "Bazer Sakhra",
    "Beidha Bordj",
    "Belaa",
    "Beni Aziz",
    "Beni Chebana",
    "Beni Fouda",
    "Beni Hocine",
    "Beni Mouhli",
    "Beni Ouartilane",
    "Bir El Arch",
    "Bir Haddada",
    "Bouandas",
    "Bougaa",
    "Bousselam",
    "Boutaleb",
    "Dehamcha",
    "Djemila",
    "Draa Kebila",
    "El Eulma",
    "El Ouldja",
    "El Ouricia",
    "Guellal",
    "Guelta Zerka",
    "Guenzet",
    "Guidjel",
    "Hamma",
    "Hammam Guergour",
    "Harbil",
    "Ksar El Abtal",
    "Maaouia",
    "Maoklane",
    "Mezloug",
    "Oued El Barad",
    "Ouled Addouane",
    "Ouled Sabor",
    "Ouled Sidi Ahmed",
    "Ouled Tebben",
    "Salah Bey",
    "Serdj El Ghoul",
    "Sétif",
    "Tachouda",
    "Talaifacene",
    "Taya",
    "Tella",
    "Tizi Nbechar",
  ],
  20: [
    "Ain El Hadjar",
    "Ain Sekhouna",
    "Ain Soltane",
    "Doui Thabet",
    "El Hassasna",
    "Hounet",
    "Maamora",
    "Moulay Larbi",
    "Ouled Brahim",
    "Ouled Khaled",
    "Saïda",
    "Sidi Amar",
    "Sidi Boubekeur",
    "Tircine",
    "Youb",
  ],
  21: [
    "Ain Cherchar",
    "Ain Kechra",
    "Azzaba",
    "Bekkouche Lakhdar",
    "Beni Bechir",
    "Beni Oulbane",
    "Bouchtata",
    "Cheraia",
    "Collo",
    "Djendel Saadi Mohamed",
    "El Ghedir",
    "El Hadaik",
    "El Harrouch",
    "Emdjez Edchich",
    "Es Sebt",
    "Fil Fila",
    "Hamadi Krouma",
    "Kerkera",
    "Oum Toub",
    "Ramdane Djamel",
    "Salah Bouchaour",
    "Sidi Mezghiche",
    "Skikda",
    "Tamalous",
    "Zerdaza",
  ],
  22: [
    "Ain Adden",
    "Ain El Berd",
    "Ain Kada",
    "Ain Thrid",
    "Aïn Tindamine",
    "Amarnas",
    "Badredine El Mokrani",
    "Belarbi",
    "Ben Badis",
    "Bir El Hammam",
    "Boudjebaa El Bordj",
    "Boukhanafis",
    "Chetouane Belaila",
    "Dhaya",
    "El Hacaiba",
    "Hassi Dahou",
    "Hassi Zehana",
    "Lamtar",
    "Makedra",
    "Mcid",
    "Merine",
    "Mezaourou",
    "Mostefa Ben Brahim",
    "Moulay Slissen",
    "Oued Sebaa",
    "Oued Sefioun",
    "Oued Taourira",
    "Ras El Ma",
    "Redjem Demouche",
    "Sehala Thaoura",
    "Sfissef",
    "Sidi Ali Benyoub",
    "Sidi Ali Boussidi",
    "Sidi Bel Abbès",
    "Sidi Brahim",
    "Sidi Chaib",
    "Sidi Dahou Dezairs",
    "Sidi Hamadouche",
    "Sidi Khaled",
    "Sidi Lahcene",
    "Sidi Yacoub",
    "Tabia",
    "Taoudmout",
    "Teghalimet",
    "Telagh",
    "Tenira",
    "Tessala",
    "Tilmouni",
    "Zerouala",
  ],
  23: [
    "Aïn Berda",
    "Annaba",
    "Chetaïbi",
    "Cheurfa",
    "El Bouni",
    "El Hadjar",
    "Eulma",
    "Oued El Aneb",
    "Seraidi",
    "Sidi Ahmedr",
    "Treat",
  ],
  24: [
    "Aïn Ben Beida",
    "Aïn Makhlouf",
    "Aïn Reggada",
    "Aïn Sandel",
    "Belkheir",
    "Ben Djarah",
    "Beni Mezline",
    "Bordj Sabat",
    "Bouati Mahmoud",
    "Bouchegouf",
    "Boumahra Ahmed",
    "Dahouara",
    "Djeballah Khemissi",
    "El Fedjoudj",
    "Guelma",
    "Hamman Nbail",
    "Héliopolis",
    "Khezarra",
    "Nechmaya",
    "Oued Cheham",
    "Oued Fragha",
    "Oued Zenati",
    "Ras El Agba",
    "Roknia",
    "Tamlouka",
  ],
  25: [
    "Aïn Abid",
    "Aïn Smara",
    "Beni Hamiden",
    "Constantine",
    "Didouche Mourad",
    "El Khroub",
    "Hamma Bouziane",
    "Ibn Ziad",
    "Messaoud Boudjriou",
    "Ouled Rahmoune",
    "Zighoud Youcef",
  ],
  26: [
    "Aïn Boucif",
    "Aïn Ouksir",
    "Aissaouia",
    "Aziz",
    "Baata",
    "Benchicao",
    "Beni Slimane",
    "Berrouaghia",
    "Bir Ben Laabed",
    "Boghar",
    "Bouaiche",
    "Bouaichoune",
    "Bouchrahil",
    "Boughezoul",
    "Bouskene",
    "Chahbounia",
    "Chelalet El Adhaoura",
    "Cheniguel",
    "Derrag",
    "Deux Bassins",
    "Djouab",
    "Draa Essamar",
    "El Azizia",
    "El Guelbelkebir",
    "El Hamdania",
    "El Omaria",
    "El Ouinet",
    "Hannacha",
    "Kef Lakhdar",
    "Khams Djouamaa",
    "Ksar El Boukhari",
    "Médéa",
    "Meghraoua",
    "Meftaha",
    "Mezerana",
    "Mihoub",
    "Ouamri",
    "Oued Harbil",
    "Ouled Antar",
    "Ouled Bouachra",
    "Ouled Brahim",
    "Ouled Deide",
    "Ouled Hellal",
    "Ouzera",
    "Rebaia",
    "Saneg",
    "Sedraia",
    "Seghouane",
    "Si Mahdjoub",
    "Sidi Damed",
    "Sidi Errabia",
    "Sidi Naamane",
    "Sidi Zahar",
    "Sidi Ziane",
    "Souagui",
    "Tablat",
    "Tafraout",
    "Tamesguida",
    "Tlatet Eddouar",
    "Zoubiria",
  ],
  27: [
    "Abdelmalek Ramdane",
    "Achaacha",
    "Aïn Boudinar",
    "Aïn Nouissy",
    "Aïn Sidi Cherif",
    "Blad Touahria",
    "Bouguirat",
    "El Hassiane",
    "Fornaka",
    "Hadjadj",
    "Khadra",
    "Kheiredine",
    "Mansourah",
    "Mesra",
    "Mostaganem",
    "Nekmaria",
    "Oued El Kheir",
    "Ouled Boughalem",
    "Ouled Maallah",
    "Safsaf",
    "Sayada",
    "Sidi Ali",
    "Sidi Belatter",
    "Sidi Lakhdar",
    "Sirat",
    "Souaflia",
    "Sour",
    "Stidia",
    "Tazgait",
  ],
  28: [
    "Aïn El Hadjel",
    "Aïn El Melh",
    "Aïn Errich",
    "Aïn Khadra",
    "Belaiba",
    "Ben Srour",
    "Beni Ilmane",
    "Benzouh",
    "Berhoum",
    "Bir Foda",
    "Bou Saada",
    "Bouti Sayah",
    "Chellal",
    "Dehahna",
    "Djebel Messaad",
    "El Hamel",
    "El Houamed",
    "Hammam Dhalaa",
    "Khettouti Sed El Djir",
    "Khoubana",
    "Maadid",
    "Maarif",
    "Magra",
    "Mcif",
    "Medjedel",
    "Msila",
    "Mtarfa",
    "Mohammed Boudiaf",
    "Ouanougha",
    "Ouled Addi Guebala",
    "Ouled Atia",
    "Ouled Derradj",
    "Ouled Madhi",
    "Ouled Mansour",
    "Ouled Sidi Brahim",
    "Ouled Slimane",
    "Oultem",
    "Sidi Aïssa",
    "Sidi Ameur",
    "Sidi Hadjeres",
    "Sidi M'Hamed",
    "Slim",
    "Souamaa",
    "Tamsa",
    "Tarmount",
    "Zarzour",
  ],
  29: [
    "Aïn Fares",
    "Aïn Fekan",
    "Aïn Ferah",
    "Aïn Fras",
    "Alaimia",
    "Aouf",
    "Benian",
    "Bou Hanifia",
    "Bou Henni",
    "Chorfa",
    "El Bordj",
    "El Ghomri",
    "El Guettena",
    "El Keurt",
    "El Menaouer",
    "Ferraguig",
    "Froha",
    "Gharrous",
    "Ghriss",
    "El Hachem",
    "Hacine",
    "Khalouia",
    "Makdha",
    "Mamounia",
    "Mascara",
    "Matemore",
    "Mocta Douz",
    "Mohammadia",
    "Nesmoth",
    "Oggaz",
    "Oued El Abtal",
    "Oued Taria",
    "Ras  Aïn Amirouche",
    "Sedjerara",
    "Sehailia",
    "Sidi Abdeldjebar",
    "Sidi Abdelmoumene",
    "Sidi Kada",
    "Sidi Boussaid",
    "Sig",
    "Tighennif",
    "Tizi",
    "Zahana",
    "Zelmata",
  ],
  30: [
    "Aïn Beida",
    "Hassi Ben Abdellah",
    "Hassi Messaoud",
    "Ngoussa",
    "Ouargla",
    "Rouissat",
    "Sidi Khouiled",
  ],
  31: [
    "Aïn  Kerma",
    "Aïn Turk",
    "Arzew",
    "Ben Freha",
    "Bethioua",
    "Bir El Djir",
    "Boufatis",
    "Bousfer",
    "Boutlelis",
    "El Ancar",
    "El Braya",
    "El karma",
    "Es Senia",
    "Gdyel",
    "Hassi Ben Okba",
    "Hassi Bounif",
    "Marsat El Hadjadj",
    "Mers El Kébir",
    "Oued Tlelat",
    "Oran",
    "Sidi Ben Yabka",
    "Sidi Chami",
    "Tafraoui",
  ],
  32: [
    "Aïn El Orak",
    "Arbaouat",
    "Boualem",
    "Bougtoub",
    "Boussemghoun",
    "Chellala",
    "Cheguig",
    "El Abiodh Sidi Cheikh",
    "El Bayadh",
    "El Bnoud",
    "El Kheiter",
    "El Mehara",
    "Ghassoul",
    "Kef El Ahmar",
    "Krakda",
    "Rogassa",
    "Sidi Ameur",
    "Sidi Slimane",
    "Sidi Tifour",
    "Stitten",
    "Tousmouline",
  ],
  33: ["Illizi"],
  34: [
    "Aïn Taghrout",
    "Aïn Tesra",
    "Belimour",
    "Ben Daoud",
    "Bir Kasdali",
    "Bordj Bou Arreridj",
    "Bordj Ghdir",
    "Bordj Zemoura",
    "El Ach",
    "El Achir",
    "El Anseur",
    "El Hamadia",
    "El Mhir",
    "Ghilassa",
    "Haraza",
    "Hasnaoua",
    "Khelil",
    "Ksour",
    "Mansoura",
    "Medjana",
    "Ouled Brahem",
    "Ouled Dahmane",
    "Ouled Sidi Brahim",
    "Rabta",
    "Ras El Oued",
    "Sidi Embarek",
    "Taglait",
    "Teniet En Nasr",
    "Tixter",
  ],
  35: [
    "Afir",
    "Ammal",
    "Baghlia",
    "Ben Choud",
    "Beni Amrane",
    "Bordj Menaiel",
    "Boudouaou",
    "Boudouaou El Bahri",
    "Boumerdès",
    "Bouzegza Keddara",
    "Chabet el Ameur",
    "Corso",
    "Dellys",
    "Djinet",
    "El Kharrouba",
    "Hammedi",
    "Isser",
    "Khemis El Khechna",
    "Larbatache",
    "Naciria",
    "Ouled Aïssa",
    "Ouled Hedadj",
    "Ouled Moussa",
    "Si Mustapha",
    "Sidi Daoud",
    "Souk El Had",
    "Taourga",
    "Thenia",
    "Tidjelabine",
    "Timezrit",
    "Zemmouri",
  ],
  36: [
    "Aïn El Assel",
    "Aïn Kerma",
    "Asfour",
    "Ben Mhidi",
    "Berrihane",
    "Bougous",
    "Bouhadjar",
    "Bouteldja",
    "Chebaita Mokhtar",
    "Chefia",
    "Chihani",
    "Drean",
    "Echatt",
    "El Aioun",
    "El Kala",
    "El Tarf",
    "Hammam Beni Salah",
    "Lac des Oiseaux",
    "Oued Zitoun",
    "Raml Souk",
    "Zerizer",
    "Zitouna",
  ],
  37: [
    "Oum el Assel",
    "Tindouf"
  ],

  38: [
    "Ammari", "Beni Chaib", "Beni Lahcene", "Boucaid", "Bordj Bou Naama",
    "Bordj El Emir Abdelkader", "Khemisti", "Larbaa", "Lardjem", "Layoune",
    "Lazharia", "Maacem", "Melaab",  "Sidi Abed",
    "Sidi Boutouchent", "Sidi Lantri", "Sidi Slimane", "Tamalaht",
    "Theniet El Had", "Tissemsilt", "Youssoufia"
  ],


39: [
  "El Oued", "Robbah", "Oued El Alenda", "Bayadha", "Nakhla",
  "Guemar", "Kouinine", "Reguiba", "Hamraia", "Taghzout",
  "Debila", "Hassani Abdelkrim", "Hassi Khelifa", "Taleb Larbi", "Douar El Ma",
  "Sidi Aoun", "Trifaoui", "Magrane", "Beni Guecha", "Ourmas",
  "El Ogla", "Mih Ouansa"
],


40: [
  "Aïn Touila", "Babar", "Baghai", "Bouhmama", "Chechar",
  "Chelia",  "El Hamma", "El Mahmal", 
  "Ensigha", "Kaïs", "Khenchela",  
  "Mtoussa", "Ouled Rechache", "Remila", "Taouzianat",
  "Yabous"
],


41: [
  "Souk Ahras", "Sedrata", "Hanancha", "Mechroha", "Ouled Driss",
  "Tiffech", "Zaarouria", "Taoura", "Drea", "Heddada",
  "Khedara", "Merahna", "Ouled Moumen", "Bir Bouhouch", "Mdaourouch",
  "Oum El Adhaim", "Aïn Zana", "Aïn Soltane", "Ouillen", "Sidi Fredj",
  "Safel El Ouiden", "Ragouba", "Khemissa", "Oued Keberit", "Terraguelt",
  "Zouabi"
],


42: [
  "Tipaza", "Menaceur", "Larhat", "Douaouda", "Bourkika",
  "Khemisti", "Aghbal", "Hadjout", "Sidi Amar", "Gouraya",
  "Nodor", "Chaiba", "Aïn Tagourait", "Cherchel", "Damous",
  "Meurad", "Fouka", "Bou Ismaïl", "Ahmar El Aïn", "Bou Haroun",
  "Sidi Ghiles", "Messelmoun", "Sidi Rached", "Koléa", "Attatba",
  "Sidi Semiane", "Beni Milleuk", "Hadjeret Ennous"
],


43: [
  "Ahmed Rachedi", "Aïn Beida Harriche", "Aïn Mellouk", "Aïn Tine", "Amira Arras",
  "Benyahia Abderrahmane", "Chelghoum Laid", "Chigara", "Derradji Bousselah",
  "El Mechira", "Elayadi Barbes", "Ferdjioua",  "Hamala",
  "Mila",  "Oued Athmania", "Oued Endja", "Oued Seguen",
  "Ouled Khalouf", "Rouached", "Sidi Khelifa", "Sidi Merouane", "Tadjenanet",
   "Telerghma", "Terrai Bainen",  "Tiberguent",
  "Yahia Beniguecha", "Zeghaia"
],


44: [
  "Aïn Benian", "Aïn Bouyahia", "Aïn Defla", "Aïn Lechiakh", "Aïn Soltane",
  "Aïn Torki", "Arib", "Belaas", "Ben Allal",
   "Bir Ould Khelifa", "Bordj Emir Khaled", "Boumedfaa", "Bourached",
  "Djelida", "Djemaa Ouled Chikh", "Djendel", "El Abadia", "El Amra",
  "El Attaf", "El Hassania", "El Maine", "Hammam Righa", "Hoceinia",
  "Khemis Miliana", "Mekhatria", "Miliana", "Oued Chorfa", "Oued Djemaa",
  "Rouina", "Sidi Lakhdar", "Tacheta Zegagha", "Tarik Ibn Ziad", "Tiberkanine",
  "Zeddine"
],


45: [
  "Naama", "Mechria", "Aïn Sefra", "Tiout", "Sfissifa",
  "Moghrar"
],


46: [
  "Aghlal", "Aïn El Arbaa", "Aïn Temouchent", "Aïn Tolba",
  "Aoubellil", "Beni Saf", "Bou Zedjar", "Chaabat El Leham", "Chentouf",
  "El Amria", "El Emir Abdelkader", "El Malah", "El Messaid",
  "Hammam Bouhadjar", "Hassasna", "Hassi El Ghella", "Oued Berkeche",
  "Oued Sabah", "Ouled Boudjemaa", "Ouled Kihal",
  "Sidi Ben Adda", "Sidi Boumedienne",  "Sidi Safi",
  "Tamzoura", "Terga"
],


47: [
  "Berriane", "Bounoura", "Dhayet Bendhahoua", "El Atteuf", "El Guerrara",
  "Ghardaïa", "Mansoura", "Metlili", "Sebseb", "Zelfana"
],


48: [
  "Aïn Rahma", "Aïn Tarek",  "Ammi Moussa", "Belassel Bouzegza",
  "Bendaoud", "Beni Dergoun", "Beni Zentis", "Dar Ben Abdellah", "Djidioua",
  "El Guettar", "El Hamadna", "El Hassi", "El Matmar", "El Ouldja",
  "Had Echkalla", "Hamri", "Kalaa", "Lahlef", "Mazouna",
  "Mediouna", "Mendes", "Merdja Sidi Abed", "Ouarizane", "Oued Essalem",
  "Oued Rhiou", "Ouled Aiche", "Oued El Djemaa", "Ouled Sidi Mihoub", "Ramka",
  "Relizane", "Sidi Khettab", "Sidi Lazreg", "Sidi MHamed Ben Ali", "Sidi MHamed Benaouda",
  "Sidi Saada", "Souk El Haad", "Yellel", "Zemmoura"
],


49: [
  "Aougrout", "Charouine", "Deldoul", "Ksar Kaddour",
  "Ouled Saïd",  "Timimoun", "Tinerkouk"
],




51: [
  "Besbes", "Chaïba", "Doucen", "Ouled Djellal", "Sidi Khaled", "Ras El Miad"
],


52: [
  "Béni Abbes", "Beni-Ikhlef", "El Ouata", "Igli", "Kerzaz", "Ksabi",
  "Ouled-Khodeir",  "Tamtert", "Timoudi"
],


53: [
  "Foggaret Ezzoua", "Inghar", "Ain Salah"
],




55: [
  "Benaceur", "Blidet Amor",  "El-Hadjira", "Megarine", 
 "Sidi Slimane", "Taibet", "Temacine", "Tebesbest", "Touggourt", "Zaouia El Abidia"
],




57: [
  "Djamaa", "El M'Ghair", "M'rara", "Oum Touyour", "Sidi Amrane",
  "Sidi Khellil", "Still", "Tenedla"
],

58: [
  "El Meniaa", "Hassi Fehal", "Hassi Gara"
],
}

// Bureaux Noest (offices) used for stop-desk delivery
export const bureauxNoest: BureauNoest[] = [
  { code: "1A", nom: "Adrar" },
  { code: "2A", nom: "Chlef" },
  { code: "3A", nom: "Laghouat" },
  { code: "3B", nom: "Laghouat (Aflou)" },
  { code: "4A", nom: "Oum El Bouaghi (Ain Mlila)" },
  { code: "4B", nom: "Oum El Bouaghi" },
  { code: "5A", nom: "Batna" },
  { code: "5B", nom: "Batna (Barika)" },
  { code: "6A", nom: "Bejaïa" },
  { code: "6B", nom: "Bejaïa (Akbou)" },
  { code: "7A", nom: "Biskra" },
  { code: "8A", nom: "Béchar" },
  { code: "9A", nom: "Blida" },
  { code: "s9B", nom: "Blida (Boufarik)" },
  { code: "10A", nom: "Bouira" },
  { code: "11A", nom: "tamanghasset" },
  { code: "12A", nom: "Tébessa" },
  { code: "13A", nom: "Tlemcen" },
  { code: "13B", nom: "Tlemcen (Maghnia)" },
  { code: "14A", nom: "Tiaret" },
  { code: "15A", nom: "Tizi Ouzou" },
  { code: "15B", nom: "Tizi Ouzou (Azazga)" },
  { code: "16A", nom: "Alger (Bir Mourad Raïs)" },
  { code: "16B", nom: "Alger (Bab Ezzouar)" },
  { code: "16C", nom: "Alger (Chéraga)" },
  { code: "16D", nom: "Alger (Reghaia)" },
  { code: "16E", nom: "Alger (Centre - Sacré-Cœur)" },
  { code: "16F", nom: "Alger (Baba Hassen)" },
  { code: "16G", nom: "Alger (Baraki)" },
  { code: "17A", nom: "Djelfa" },
  { code: "18A", nom: "Jijel" },
  { code: "19A", nom: "Sétif" },
  { code: "19B", nom: "Sétif (El Eulma)" },
  { code: "19C", nom: "Sétif (Ain Oulmene)" },
  { code: "19RE", nom: "Sétif (Guidjel)" },
  { code: "20A", nom: "Saïda" },
  { code: "21A", nom: "Skikda" },
  { code: "22A", nom: "Sidi Bel Abbès" },
  { code: "23A", nom: "Annaba" },
  { code: "24A", nom: "Guelma" },
  { code: "25A", nom: "Constantine (Zouaghi)" },
  { code: "25B", nom: "Constantine (Ali Mendjeli)" },
  { code: "25C", nom: "Constantine" },
  { code: "26A", nom: "Médéa" },
  { code: "27A", nom: "Mostaganem" },
  { code: "28A", nom: "M'sila" },
  { code: "28B", nom: "M'sila (Bousaada)" },
  { code: "29A", nom: "Mascara (Mohammadia)" },
  { code: "29B", nom: "Mascara (Ville)" },
  { code: "30A", nom: "Ouargla" },
  { code: "31A", nom: "Oran (Maraval)" },
  { code: "31B", nom: "Oran (Bir El Djir)" },
  { code: "31C", nom: "Oran (Gambetta)" },
  { code: "32A", nom: "El Bayadh" },
  { code: "33A", nom: "Illizi" },
  { code: "34A", nom: "Bordj Bou Arreridj" },
  { code: "35A", nom: "Boumerdès" },
  { code: "35B", nom: "Boumerdès (Ouled Moussa)" },
  { code: "36A", nom: "El Taref" },
  { code: "37A", nom: "Tindouf" },
  { code: "38A", nom: "Tissemsilt" },
  { code: "39A", nom: "El Oued" },
  { code: "40A", nom: "Khenchela" },
  { code: "41A", nom: "Souk Ahras" },
  { code: "42A", nom: "Tipaza" },
  { code: "43A", nom: "Mila" },
  { code: "43B", nom: "Mila (Chelghoum El Aid)" },
  { code: "44A", nom: "Ain Defla" },
  { code: "44B", nom: "Ain Defla (Khemis Miliana)" },
  { code: "45A", nom: "Naâma (Mécheria)" },
  { code: "46A", nom: "Aïn Témouchent" },
  { code: "47A", nom: "Ghardaïa" },
  { code: "48A", nom: "Relizane" },
  { code: "49A", nom: "Timimoun" },
  { code: "51A", nom: "Ouled Djellal" },
  { code: "52A", nom: "Béni Abbès" },
  { code: "53A", nom: "In Salah" },
  { code: "55A", nom: "Touggourt" },
  { code: "58A", nom: "El Meniaa" },
]
